variables:
  CI_SSH_KEY: "./gitlab_key.pem"

junit:
  image: maven:3.6.1-jdk-11 # docker image with Maven
  before_script:
    - . setup-mvn-proxy.sh
    - chmod 400 $CI_SSH_KEY
  script:
    - mvn clean
    - mvn install
    - mvn test
    - mvn compile
    - ls /builds/p1709456/mifprojet/target
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY /builds/p1709456/mifprojet/target/mifprojetgp7.war gitlabci@192.168.74.206:/opt/tomcat/webapps/mifprojetgp7_war.war
